- name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install System Dependencies (FFmpeg)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade yt-dlp

      - name: Create Cookies File from Secret
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt
